-- Core lookups and entities
CREATE TABLE BRAND (
  BRAND_ID      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME          VARCHAR2(50) NOT NULL,
  CONSTRAINT UQ_BRAND_NAME UNIQUE (NAME)
);

CREATE TABLE COMPUTER_MODEL (
  MODEL_ID      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BRAND_ID      NUMBER(10) NOT NULL,
  MODEL_NAME    VARCHAR2(50) NOT NULL,
  CONSTRAINT UQ_MODEL_BRAND_NAME UNIQUE (BRAND_ID, MODEL_NAME),
  CONSTRAINT FK_MODEL_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (BRAND_ID)
);

CREATE TABLE MOUSE_TYPE (
  MOUSE_TYPE_CODE VARCHAR2(10) PRIMARY KEY,
  DESCRIPTION     VARCHAR2(50) NOT NULL
);

CREATE TABLE COMPUTER (
  COMPUTER_ID      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MODEL_ID         NUMBER(10) NOT NULL,
  COMPUTER_NUMBER  VARCHAR2(20) NOT NULL,
  MOUSE_TYPE_CODE  VARCHAR2(10) NOT NULL,
  CONSTRAINT UQ_COMPUTER_NUMBER UNIQUE (COMPUTER_NUMBER),
  CONSTRAINT FK_COMPUTER_MODEL FOREIGN KEY (MODEL_ID) REFERENCES COMPUTER_MODEL (MODEL_ID),
  CONSTRAINT FK_COMPUTER_MOUSE_TYPE FOREIGN KEY (MOUSE_TYPE_CODE) REFERENCES MOUSE_TYPE (MOUSE_TYPE_CODE)
);

CREATE TABLE POSTAL_CODE (
  POSTAL_CODE CHAR(4) PRIMARY KEY,
  CITY        VARCHAR2(50) NOT NULL
);

CREATE TABLE STUDENT_CLASS (
  CLASS_ID    NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLASS_CODE  VARCHAR2(20) NOT NULL,
  CLASS_NAME  VARCHAR2(100),
  CONSTRAINT UQ_CLASS_CODE UNIQUE (CLASS_CODE)
);

CREATE TABLE STUDENT (
  STUDENT_ID      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_NUMBER  VARCHAR2(20) NOT NULL,
  FULL_NAME       VARCHAR2(100) NOT NULL,
  ADDRESS_LINE    VARCHAR2(100),
  POSTAL_CODE     CHAR(4),
  CPR_NUMBER      VARCHAR2(11),
  EMAIL           VARCHAR2(320),
  CLASS_ID        NUMBER(10),
  CONSTRAINT UQ_STUDENT_NUMBER UNIQUE (STUDENT_NUMBER),
  CONSTRAINT UQ_STUDENT_CPR UNIQUE (CPR_NUMBER),
  CONSTRAINT UQ_STUDENT_EMAIL UNIQUE (EMAIL),
  CONSTRAINT FK_STUDENT_POSTAL_CODE FOREIGN KEY (POSTAL_CODE) REFERENCES POSTAL_CODE (POSTAL_CODE),
  CONSTRAINT FK_STUDENT_CLASS FOREIGN KEY (CLASS_ID) REFERENCES STUDENT_CLASS (CLASS_ID),
  CONSTRAINT CHK_STUDENT_CPR_FORMAT CHECK (
    CPR_NUMBER IS NULL OR REGEXP_LIKE(CPR_NUMBER, '^\d{6}-?\d{4}$')
  ),
  CONSTRAINT CHK_STUDENT_EMAIL_FORMAT CHECK (
    EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[^@]+@[^@]+\.[^@]+$')
  )
);

CREATE TABLE LOAN (
  LOAN_ID      NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_ID   NUMBER(10) NOT NULL,
  COMPUTER_ID  NUMBER(10) NOT NULL,
  LOAN_DATE    DATE NOT NULL,
  DUE_DATE     DATE NOT NULL,
  RETURN_DATE  DATE,
  NOTES        CLOB,
  CONSTRAINT FK_LOAN_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
  CONSTRAINT FK_LOAN_COMPUTER FOREIGN KEY (COMPUTER_ID) REFERENCES COMPUTER (COMPUTER_ID),
  CONSTRAINT CHK_LOAN_DATES CHECK (DUE_DATE >= LOAN_DATE),
  CONSTRAINT CHK_LOAN_RETURN_DATE CHECK (RETURN_DATE IS NULL OR RETURN_DATE >= LOAN_DATE)
);

-- One active loan per computer (RETURN_DATE IS NULL)
CREATE UNIQUE INDEX UX_LOAN_ACTIVE_COMPUTER
  ON LOAN (CASE WHEN RETURN_DATE IS NULL THEN COMPUTER_ID ELSE NULL END);

-- Extensions (optional but included)
CREATE TABLE BORROWER_BLACKLIST (
  BLACKLIST_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_ID   NUMBER(10) NOT NULL,
  START_DATE   DATE NOT NULL,
  END_DATE     DATE,
  REASON       CLOB,
  CONSTRAINT FK_BLACKLIST_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
  CONSTRAINT CHK_BLACKLIST_RANGE CHECK (END_DATE IS NULL OR END_DATE >= START_DATE)
);

CREATE TABLE TEACHER (
  TEACHER_ID  NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FULL_NAME   VARCHAR2(100) NOT NULL,
  EMAIL       VARCHAR2(320),
  CONSTRAINT UQ_TEACHER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CHK_TEACHER_EMAIL_FORMAT CHECK (
    EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[^@]+@[^@]+\.[^@]+$')
  )
);

CREATE TABLE RESERVATION (
  RESERVATION_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TEACHER_ID     NUMBER(10) NOT NULL,
  START_DATE     DATE NOT NULL,
  END_DATE       DATE NOT NULL,
  QUANTITY       NUMBER(5) NOT NULL,
  STATUS         VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
  NOTES          CLOB,
  CONSTRAINT FK_RES_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (TEACHER_ID),
  CONSTRAINT CHK_RES_RANGE CHECK (END_DATE >= START_DATE),
  CONSTRAINT CHK_RES_QUANTITY CHECK (QUANTITY > 0)
);

CREATE TABLE RESERVATION_ITEM (
  RESERVATION_ITEM_ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RESERVATION_ID      NUMBER(10) NOT NULL,
  COMPUTER_ID         NUMBER(10) NOT NULL,
  CONSTRAINT FK_RES_ITEM_RES FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID),
  CONSTRAINT FK_RES_ITEM_COMPUTER FOREIGN KEY (COMPUTER_ID) REFERENCES COMPUTER (COMPUTER_ID),
  CONSTRAINT UQ_RES_ITEM UNIQUE (RESERVATION_ID, COMPUTER_ID)
);

CREATE TABLE EMAIL_QUEUE (
  EMAIL_ID    NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  RECIPIENT   VARCHAR2(320) NOT NULL,
  SUBJECT     VARCHAR2(200) NOT NULL,
  BODY        CLOB NOT NULL,
  QUEUED_AT   DATE DEFAULT SYSDATE NOT NULL,
  SENT_AT     DATE
);

-- Helpful indexes
CREATE INDEX IX_MODEL_BRAND ON COMPUTER_MODEL (BRAND_ID);
CREATE INDEX IX_COMPUTER_MODEL ON COMPUTER (MODEL_ID);
CREATE INDEX IX_COMPUTER_MOUSE ON COMPUTER (MOUSE_TYPE_CODE);
CREATE INDEX IX_STUDENT_POSTAL ON STUDENT (POSTAL_CODE);
CREATE INDEX IX_STUDENT_CLASS ON STUDENT (CLASS_ID);
CREATE INDEX IX_LOAN_STUDENT ON LOAN (STUDENT_ID);
CREATE INDEX IX_LOAN_COMPUTER ON LOAN (COMPUTER_ID);
CREATE INDEX IX_BLACKLIST_STUDENT ON BORROWER_BLACKLIST (STUDENT_ID);
CREATE INDEX IX_RES_TEACHER ON RESERVATION (TEACHER_ID);
CREATE INDEX IX_RES_ITEM_RES ON RESERVATION_ITEM (RESERVATION_ID);
CREATE INDEX IX_RES_ITEM_COMP ON RESERVATION_ITEM (COMPUTER_ID);

-- Triggers
CREATE OR REPLACE TRIGGER TRG_LOAN_ENFORCE_BLACKLIST
BEFORE INSERT ON LOAN
FOR EACH ROW
DECLARE
  v_blacklisted NUMBER;
  v_overdue     NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_blacklisted
    FROM BORROWER_BLACKLIST b
   WHERE b.STUDENT_ID = :NEW.STUDENT_ID
     AND b.START_DATE <= SYSDATE
     AND (b.END_DATE IS NULL OR b.END_DATE >= SYSDATE);
  IF v_blacklisted > 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Student is blacklisted and cannot borrow a computer at this time.');
  END IF;

  SELECT COUNT(*) INTO v_overdue
    FROM LOAN l
   WHERE l.STUDENT_ID = :NEW.STUDENT_ID
     AND l.RETURN_DATE IS NULL
     AND l.DUE_DATE < TRUNC(SYSDATE);
  IF v_overdue > 0 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Student has overdue loans and cannot borrow a new computer.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOAN_DEFAULT_DUE_DATE
BEFORE INSERT ON LOAN
FOR EACH ROW
BEGIN
  IF :NEW.DUE_DATE IS NULL THEN
    :NEW.DUE_DATE := :NEW.LOAN_DATE + 14;
  END IF;
END;
/

-- Minimal seed data (safe to re-run)
MERGE INTO MOUSE_TYPE d USING (SELECT 'OPTICAL' code, 'Optical mouse' descr FROM dual) s
ON (d.MOUSE_TYPE_CODE = s.code)
WHEN NOT MATCHED THEN INSERT (MOUSE_TYPE_CODE, DESCRIPTION) VALUES (s.code, s.descr);

MERGE INTO MOUSE_TYPE d USING (SELECT 'STANDARD' code, 'Standard/ball mouse' descr FROM dual) s
ON (d.MOUSE_TYPE_CODE = s.code)
WHEN NOT MATCHED THEN INSERT (MOUSE_TYPE_CODE, DESCRIPTION) VALUES (s.code, s.descr);

MERGE INTO MOUSE_TYPE d USING (SELECT 'NONE' code, 'No mouse' descr FROM dual) s
ON (d.MOUSE_TYPE_CODE = s.code)
WHEN NOT MATCHED THEN INSERT (MOUSE_TYPE_CODE, DESCRIPTION) VALUES (s.code, s.descr);

MERGE INTO POSTAL_CODE d USING (SELECT '2100' pc, 'København Ø' city FROM dual) s
ON (d.POSTAL_CODE = s.pc)
WHEN NOT MATCHED THEN INSERT (POSTAL_CODE, CITY) VALUES (s.pc, s.city);

MERGE INTO POSTAL_CODE d USING (SELECT '8000' pc, 'Aarhus C' city FROM dual) s
ON (d.POSTAL_CODE = s.pc)
WHEN NOT MATCHED THEN INSERT (POSTAL_CODE, CITY) VALUES (s.pc, s.city);

MERGE INTO BRAND d USING (SELECT 'DELL' name FROM dual) s
ON (d.NAME = s.name)
WHEN NOT MATCHED THEN INSERT (NAME) VALUES (s.name);

MERGE INTO BRAND d USING (SELECT 'HP' name FROM dual) s
ON (d.NAME = s.name)
WHEN NOT MATCHED THEN INSERT (NAME) VALUES (s.name);

INSERT /*+ ignore_row_on_dupkey_index(COMPUTER_MODEL, UQ_MODEL_BRAND_NAME) */ INTO COMPUTER_MODEL (BRAND_ID, MODEL_NAME)
  SELECT BRAND_ID, 'Inspiron 9300' FROM BRAND WHERE NAME = 'DELL';

INSERT /*+ ignore_row_on_dupkey_index(COMPUTER_MODEL, UQ_MODEL_BRAND_NAME) */ INTO COMPUTER_MODEL (BRAND_ID, MODEL_NAME)
  SELECT BRAND_ID, 'EliteBook 840' FROM BRAND WHERE NAME = 'HP';

INSERT /*+ ignore_row_on_dupkey_index(STUDENT_CLASS, UQ_CLASS_CODE) */ INTO STUDENT_CLASS (CLASS_CODE, CLASS_NAME)
  VALUES ('1A', '1A Gymnasium');

INSERT /*+ ignore_row_on_dupkey_index(STUDENT_CLASS, UQ_CLASS_CODE) */ INTO STUDENT_CLASS (CLASS_CODE, CLASS_NAME)
  VALUES ('2B', '2B Gymnasium');

COMMIT;