-- Run as SYS with role SYSDBA, connected to your PDB (XEPDB1/FREEPDB1/XE).
-- If needed: ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER LENDING IDENTIFIED BY "SchoolLending!2025"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER TO LENDING;
-- Optional later: GRANT CREATE PROCEDURE TO LENDING;

-- Verify (optional):
-- SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME='LENDING';