-- Create one computer
INSERT INTO COMPUTER (MODEL_ID, COMPUTER_NUMBER, MOUSE_TYPE_CODE)
SELECT MODEL_ID, 'PC-0722', 'OPTICAL'
FROM COMPUTER_MODEL
WHERE MODEL_NAME = 'Inspiron 9300'
FETCH FIRST 1 ROWS ONLY;

-- Create one student
INSERT INTO STUDENT (STUDENT_NUMBER, FULL_NAME, ADDRESS_LINE, POSTAL_CODE, CPR_NUMBER, EMAIL, CLASS_ID)
VALUES (
  'S-1001', 'Anna Hansen', 'Examplevej 12', '2100', '010203-1234', 'anna@example.com',
  (SELECT CLASS_ID FROM STUDENT_CLASS WHERE CLASS_CODE='1A')
);

COMMIT;

-- Register a loan for today (due date auto-fills to +14 by trigger if not provided)
INSERT INTO LOAN (STUDENT_ID, COMPUTER_ID, LOAN_DATE)
SELECT s.STUDENT_ID, c.COMPUTER_ID, TRUNC(SYSDATE)
FROM STUDENT s
JOIN COMPUTER c ON c.COMPUTER_NUMBER='PC-0722'
WHERE s.STUDENT_NUMBER='S-1001';

COMMIT;

-- Required views:
SELECT * FROM V_ACTIVE_LOANS;
SELECT * FROM V_AVAILABLE_COMPUTERS;  -- should NOT list PC-0722 now
SELECT * FROM V_LOAN_HISTORY;

-- Optional: simulate overdue
-- UPDATE LOAN
-- SET DUE_DATE = TRUNC(SYSDATE) - 1
-- WHERE LOAN_ID = (SELECT MAX(LOAN_ID) FROM LOAN);
-- COMMIT;
-- SELECT * FROM V_OVERDUE_LOANS;