CREATE OR REPLACE VIEW V_ACTIVE_LOANS AS
SELECT
  l.LOAN_ID,
  l.LOAN_DATE,
  l.DUE_DATE,
  s.STUDENT_ID,
  s.STUDENT_NUMBER,
  s.FULL_NAME AS STUDENT_NAME,
  s.EMAIL AS STUDENT_EMAIL,
  c.COMPUTER_ID,
  c.COMPUTER_NUMBER,
  b.NAME AS BRAND,
  m.MODEL_NAME
FROM LOAN l
JOIN STUDENT s ON s.STUDENT_ID = l.STUDENT_ID
JOIN COMPUTER c ON c.COMPUTER_ID = l.COMPUTER_ID
JOIN COMPUTER_MODEL m ON m.MODEL_ID = c.MODEL_ID
JOIN BRAND b ON b.BRAND_ID = m.BRAND_ID
WHERE l.RETURN_DATE IS NULL;

CREATE OR REPLACE VIEW V_OVERDUE_LOANS AS
SELECT
  a.*,
  (TRUNC(SYSDATE) - a.DUE_DATE) AS DAYS_OVERDUE
FROM V_ACTIVE_LOANS a
WHERE a.DUE_DATE < TRUNC(SYSDATE);

CREATE OR REPLACE VIEW V_AVAILABLE_COMPUTERS AS
SELECT
  c.COMPUTER_ID,
  c.COMPUTER_NUMBER,
  b.NAME AS BRAND,
  m.MODEL_NAME,
  c.MOUSE_TYPE_CODE
FROM COMPUTER c
JOIN COMPUTER_MODEL m ON m.MODEL_ID = c.MODEL_ID
JOIN BRAND b ON b.BRAND_ID = m.BRAND_ID
WHERE NOT EXISTS (
  SELECT 1 FROM LOAN l WHERE l.COMPUTER_ID = c.COMPUTER_ID AND l.RETURN_DATE IS NULL
);

CREATE OR REPLACE VIEW V_LOAN_HISTORY AS
SELECT
  l.LOAN_ID,
  s.STUDENT_NUMBER,
  s.FULL_NAME AS STUDENT_NAME,
  c.COMPUTER_NUMBER,
  b.NAME AS BRAND,
  m.MODEL_NAME,
  l.LOAN_DATE,
  l.DUE_DATE,
  l.RETURN_DATE,
  CASE WHEN l.RETURN_DATE IS NULL THEN 'ACTIVE' ELSE 'RETURNED' END AS LOAN_STATUS
FROM LOAN l
JOIN STUDENT s ON s.STUDENT_ID = l.STUDENT_ID
JOIN COMPUTER c ON c.COMPUTER_ID = l.COMPUTER_ID
JOIN COMPUTER_MODEL m ON m.MODEL_ID = c.MODEL_ID
JOIN BRAND b ON b.BRAND_ID = m.BRAND_ID;